name = "bioarchive"
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]


[[kv_namespaces]]
binding = "BIOARCHIVE_CACHE"
id = "0e78e1d8be9d42e08e340193683f81e9"

[vars]
SITE_NAME = "BioArchive"
DRIVE_FOLDER_ID = "1AcpuO4CFHMAttp1gYOgjJH7GbOnQg9ve"
DRIVE_QUARANTINE_FOLDER_ID = "1_WpOQsN42kn5mbrz2rwEpdViucTYvWVX"
SHEET_ID = "1-SEUn_HG62-T06ZRV_vkeHZ5eDTOi4Fuu566KvDDMOo"
BOOKS_DRIVE_FOLDER_ID = "1h8SeGTJgtoxD57JXxYG_wkOfeAeDms4d"
BACKUP_DRIVE_FOLDER_ID = "1bb8KAvBfnRXMi44cJCYY54aGEC952NAL"
GOOGLE_CLIENT_ID = "886964169969-qkr86185poeoo1pp2o8bihvlr1vbdf00.apps.googleusercontent.com"
NEXT_PUBLIC_GOOGLE_CLIENT_ID = "886964169969-qkr86185poeoo1pp2o8bihvlr1vbdf00.apps.googleusercontent.com"
